#! /usr/bin/env ruby

# frozen_string_literal: true

# TODO: rename this and allow various files to be passed int as arguments

require 'pathname'

$LOAD_PATH.unshift(Pathname.new(__dir__) + 'lib/eus')

require 'solver'
solution =
  Eus::Solver.new((Pathname.new(__dir__) + 'boards/annoyingly_hard').open).solve
puts solution.inspect
